Add videos and slides
cilium/ebpf.io-summit pull request #53
Opened 2022-11-01 12:52 UTC by nerucheva

**Describe what changes this pull request brings**
This PR removes the schedule and adds a section with links to videos and slides for talks.

**Steps to test**
1. Open [the page](https://BRANCH_NAME--PROJECT_NAME.netlify.app/PAGE_URL)
2. Confirm that everything looks and works as expected

<details> 
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/68022519/199235644-c918adf6-a507-41c9-b590-51f54229ff05.png) 
</details> 

**References**

1. [Design](https://www.figma.com/file/L49LK6NTH0A5PVwGSW25ub/EBPF-Summit?node-id=2252%3A4664)

2022-11-01 14:59 UTC, vannyle requested changes
The PR looks great, just a few nitpick comments

2022-11-01 14:59 UTC, vannyle commented on src/components/pages/summit-2022/talks/talks.jsx
> +              className="text-xl text-[#FF9800] transition-colors duration-200 hover:text-[#FFAD33]"
This color `[#FF9800]` should be added to tailwind config

2022-11-01 14:59 UTC, vannyle commented on src/components/pages/summit-2022/talks/talks.jsx
> +          <div className="mt-14  text-center">
```suggestion
          <div className="mt-14 text-center">
```

2022-11-01 14:59 UTC, vannyle commented on src/components/pages/summit-2022/talks/talks.jsx
> +                    className="items-center h-11 leading-none lg:h-10 md:text-base lg:ml-5 rounded-lg py-3.5 px-5 text-base"
```suggestion
                    className="items-center h-11 leading-none lg:h-10 md:text-base lg:ml-5 rounded-lg py-3.5 px-5"
```

2022-11-01 14:59 UTC, vannyle commented on src/components/pages/summit-2022/talks/talks.jsx
> +                    size="xs"
```suggestion
                    size="sm"
```

2022-11-01 14:59 UTC, vannyle commented on src/pages/summit-2022.jsx
> +  items: talksData.filter((item) => !item.keynotes),
What is this filter for? I couldn't find the item with keynotes at all

2022-11-01 14:59 UTC, vannyle commented on src/components/pages/summit-2022/talks/talks.jsx
> +                  className="rounded-lg py-3.5 leading-none px-5 text-base"
No need to overwrite the font-size once you have size for the button

2022-11-02 09:32 UTC, vannyle approved these changes
Nice job! 💯

2022-11-02 10:00 UTC, k8isdead approved these changes

2022-11-04 15:03 UTC, merged